version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'INSTALL_ZSH' below affects the image in the Dockerfile
      args: 
        # [Choice] Update 'VARIANT' to pick a version
        # https://mcr.microsoft.com/v2/azure-functions/dotnet/tags/list
        # VARIANT: latest
        # INSTALL_ZSH: "true"
        # UPGRADE_PACKAGES: "true"
         
    environment:
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
       
    volumes:
      # Forwards the local Docker socket to the container.
      # - /var/run/docker.sock:/var/run/docker-host.sock 
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    # volumes:
    #   - storage-data:/data
    network_mode: host

# volumes:
#   storage-data:

# networks:
#   default:
#     external:
#       name: bridge